### ISSUE TITLE
how to handle onClick - question.

### ISSUE THREAD

**Issue by FDiskas** [Sharlaan/material-ui-superselectfield#64]
Hi,
my main problem is that I need to fetch the list only if a user is trying to open the selection list.
Currently it's possible to do so only on componentDidMount. But in my case there is like 50 superselectfields and all of them should fetch the data - so some kind of brute force happening.

Could you explain the clear way to do so?
Attributes like onClick, onFocus, onTap does not works.

**Comment by MaximilianPichler** [comment]
Hi!
I've implemented an onMenuOpen event. Check it out on my [fork](https://github.com/MaximilianPichler/material-ui-selectfield)

**Comment by FDiskas** [comment]
Nice fork, could you please make a release to npm... :flower_playing_cards:

**Comment by TarikHuber** [comment]
There is already one: material-ui-selectfield
We are using it in production.

**Comment by FDiskas** [comment]
Thanks

**Comment by Sharlaan** [comment]
Just released v1.6.0 including onMenuOpen, please check it.

But in your case, if your "50 selectfields" all share same data, or even only 5 different datasets, i would strongly encourage to avoid using onMenuOpen on each component.
Instead fetch your shared datasets on page load in componentDidMount, then reference each selectField with its corresponding dataset.
An alternative method would be to use cache, ie put your fetch method in onMenuOpen but include a check if dataset already exist in cache, if yes load it directly, otherwise make the server request.

**Comment by FDiskas** [comment]
tried onMenuOpen to fetch data - with no luck. On first click dropdown is not opened, but on second is ok works. Can you add an example of async data?

**Comment by FDiskas** [comment]
So how I should do to prevent user to click on dropdown twice to see the actuals results
![ezgif com-optimize 2](https://user-images.githubusercontent.com/468006/33023882-3b43d6b8-ce12-11e7-91c0-7d173d393077.gif)
